### ISSUE TITLE
how to get the topic and use gazebo

### ISSUE THREAD

**Issue by gaoxiaohuicoco** [jr-robotics/robo-gym#23]
1.when use gui=true,it launch rviz,but i want to launch gazebo to simulation
2.apparently,the project use ros,but in a new terminal,rostopic list ,it show 'ERROR: Unable to communicate with master!',i guess that is related to tmux.
3.please give more examples!!!

**Comment by matteolucchi** [comment]
Hi @gaoxiaohuicoco, thank you for using robot-gym.


> 1.when use gui=true,it launch rviz,but i want to launch gazebo to simulation

In all the environments you can modify the cmd line (for example here https://github.com/jr-robotics/robo-gym/blob/cf6af29dd2a7542251ce42f90540c71e518836f0/robo_gym/envs/ur10/ur10.py#L449-L451) but you can change that by specifying the following arguments `rviz_gui` and `gazebo_gui`, by default only `rviz_gui` is set to true but you can have it like you prefer and have either one of them or both. 

> 2.apparently,the project use ros,but in a new terminal,rostopic list ,it show 'ERROR: Unable to communicate with master!',i guess that is related to tmux.

Yes, all the ROS part runs in a tmux server. You can access the server with `tmux -L ServerManager` and move around the different sessions with the standard tmux commands (https://tmuxcheatsheet.com)

> 3.please give more examples!!!
We are working on that, if you a specific idea about an example that you would like to see please let us know
