### ISSUE TITLE
What are the benefits of using RPC instead of ros communication?

### ISSUE THREAD

**Issue by cgdsss** [jr-robotics/robo-gym#41]
I think you use ROS to receive simulation messages, and then use RPC to transmit them to the gym environment. Why don't you send the ROS messages directly to the gym environment ? Is it just because ROS does not support Python3? Are there other considerations?

**Comment by matteolucchi** [comment]
Hi @cgdsss ! Thank you for your interest in robo-gym! 

>  Is it just because ROS does not support Python3?
This was one of the  motivations when we started development although now this is solved as ROS Noetic is based on Python 3.

The other reason was that we want to be language agnostic, and even though right now we only use Gazebo and ROS, having gRPC as a communication layer allows us to develop Robot Servers implemented in any [language supported by gRPC](https://grpc.io/docs/languages/), this means that we could use simulators and/or robot that do not provide a ROS interface

I hope this answers your question.

Cheers, 
Matteo
